apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
    image.openshift.io/triggers: '[{"from":{"kind":"ImageStreamTag","name":"httpd:2.4-el8","namespace":"openshift"},"fieldPath":"spec.template.spec.containers[?(@.name==\"httpd\")].image"}]'
    openshift.io/generated-by: OpenShiftNewApp
  creationTimestamp: "2021-11-30T09:00:22Z"
  generation: 2
  labels:
    app: httpd
    app.kubernetes.io/component: httpd
    app.kubernetes.io/instance: httpd
    manager: openshift-controller-manager
    operation: Update
    time: "2021-11-30T09:00:22Z"
  name: httpd
  namespace: httpd-invitado
  resourceVersion: "448733"
  selfLink: /apis/apps/v1/namespaces/httpd-invitado/deployments/httpd
  uid: 3bbaaa0f-c2be-442e-a965-6274ca322c5d
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      deployment: httpd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftNewApp
      creationTimestamp: null
      labels:
        deployment: httpd
    spec:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/openshift/httpd@sha256:602c9f25b0c50f3de680b98f47286861deebf0dfc5f05b57071274153b0849d1
        imagePullPolicy: IfNotPresent
        name: httpd
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30










apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-invitado
spec:
  replicas: 1
  selector:
    matchLabels:
      app: httpd-invitado
  template:
    metadata:
      labels:
        app: httpd-invitado
    spec:
      containers:
      containers:
      - image: image-registry.openshift-image-registry.svc:5000/openshift/httpd@sha256:602c9f25b0c50f3de680b98f47286861deebf0dfc5f05b57071274153b0849d1
        imagePullPolicy: IfNotPresent
        name: httpd
        ports:
        - containerPort: 8080
          protocol: TCP
        - containerPort: 8443
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
